language: node_js

node_js:
    - "6"
    - "8"
    - "9"

cache: yarn

script:
    - npm run lint
    - npm run build

jobs:
    include:
        - stage: Publish docs
          if: type = push AND branch = master
          script: travis/publishDocs.sh

notifications:
    webhooks:
        urls:
            - $DISCORD_WEBHOOK_URL
        on_success: change
        on_failure: always
        on_start: never
        on_cancel: never
        on_error: always
